<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;


class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $now = Carbon::now()->toDateTimeString();

        $municipios = [
            ['departamento_id' => 1, 'codigo' => 1, 'nombre' => 'MEDELLIN','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 2, 'nombre' => 'ABEJORRAL','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 4, 'nombre' => 'ABRIAQUI','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 21, 'nombre' => 'ALEJANDRIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 30, 'nombre' => 'AMAGA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 31, 'nombre' => 'AMALFI','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 34, 'nombre' => 'ANDES','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 36, 'nombre' => 'ANGELOPOLIS','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 38, 'nombre' => 'ANGOSTURA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 40, 'nombre' => 'ANORI','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 42, 'nombre' => 'ANTIOQUIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 44, 'nombre' => 'ANZA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 45, 'nombre' => 'APARTADO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 51, 'nombre' => 'ARBOLETES','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 55, 'nombre' => 'ARGELIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 59, 'nombre' => 'ARMENIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 79, 'nombre' => 'BARBOSA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 86, 'nombre' => 'BELMIRA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 88, 'nombre' => 'BELLO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 91, 'nombre' => 'BETANIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 93, 'nombre' => 'BETULIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 101, 'nombre' => 'BOLIVAR','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 107, 'nombre' => 'BRICEÑO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 113, 'nombre' => 'BURITICA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 120, 'nombre' => 'CACERES','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 125, 'nombre' => 'CAICEDO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 129, 'nombre' => 'CALDAS','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 134, 'nombre' => 'CAMPAMENTO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 138, 'nombre' => 'CAÑASGORDAS','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 142, 'nombre' => 'CARACOLI','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 145, 'nombre' => 'CARAMANTA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 147, 'nombre' => 'CAREPA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 148, 'nombre' => 'CARMEN DE VIBORAL','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 150, 'nombre' => 'CAROLINA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 154, 'nombre' => 'CAUCASIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 172, 'nombre' => 'CHIGORODO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 190, 'nombre' => 'CISNEROS','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 197, 'nombre' => 'COCORNA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 206, 'nombre' => 'CONCEPCION','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 209, 'nombre' => 'CONCORDIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 212, 'nombre' => 'COPACABANA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 234, 'nombre' => 'DABEIBA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 237, 'nombre' => 'DON MATIAS','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 240, 'nombre' => 'EBEJICO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 250, 'nombre' => 'EL BAGRE','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 264, 'nombre' => 'ENTRERRIOS','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 266, 'nombre' => 'ENVIGADO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 282, 'nombre' => 'FREDONIA','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 284, 'nombre' => 'FRONTINO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 306, 'nombre' => 'GIRALDO','created_at' => $now, 'updated_at' => $now ],
            ['departamento_id' => 1, 'codigo' => 308, 'nombre' => 'GIRARDOTA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 310, 'nombre' => 'GOMEZ PLATA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 313, 'nombre' => 'GRANADA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 315, 'nombre' => 'GUADALUPE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 318, 'nombre' => 'GUARNE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 321, 'nombre' => 'GUATAPE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 347, 'nombre' => 'HELICONIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 353, 'nombre' => 'HISPANIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 360, 'nombre' => 'ITAGUI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 361, 'nombre' => 'ITUANGO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 364, 'nombre' => 'JARDIN', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 368, 'nombre' => 'JERICO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 376, 'nombre' => 'LA CEJA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 380, 'nombre' => 'LA ESTRELLA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 390, 'nombre' => 'LA PINTADA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 400, 'nombre' => 'LA UNION', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 411, 'nombre' => 'LIBORINA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 425, 'nombre' => 'MACEO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 440, 'nombre' => 'MARINILLA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 467, 'nombre' => 'MONTEBELLO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 475, 'nombre' => 'MURINDO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 480, 'nombre' => 'MUTATA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 483, 'nombre' => 'NARIÑO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 490, 'nombre' => 'NECOCLI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 495, 'nombre' => 'NECHI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 501, 'nombre' => 'OLAYA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 541, 'nombre' => 'PEÑOL', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 543, 'nombre' => 'PEQUE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 576, 'nombre' => 'PUEBLORRICO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 579, 'nombre' => 'PUERTO BERRIO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 585, 'nombre' => 'PUERTO NARE (LA MAGDALENA)', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 591, 'nombre' => 'PUERTO TRIUNFO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 604, 'nombre' => 'REMEDIOS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 607, 'nombre' => 'RETIRO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 615, 'nombre' => 'RIONEGRO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 628, 'nombre' => 'SABANALARGA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 631, 'nombre' => 'SABANETA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 642, 'nombre' => 'SALGAR', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 647, 'nombre' => 'SAN ANDRES', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 649, 'nombre' => 'SAN CARLOS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 652, 'nombre' => 'SAN FRANCISCO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 656, 'nombre' => 'SAN JERONIMO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 658, 'nombre' => 'SAN JOSE DE LA MONTAÑA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 659, 'nombre' => 'SAN JUAN DE URABA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 660, 'nombre' => 'SAN LUIS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 664, 'nombre' => 'SAN PEDRO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 665, 'nombre' => 'SAN PEDRO DE URABA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 667, 'nombre' => 'SAN RAFAEL', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 670, 'nombre' => 'SAN ROQUE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 674, 'nombre' => 'SAN VICENTE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 679, 'nombre' => 'SANTA BARBARA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 686, 'nombre' => 'SANTA ROSA DE OSOS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 690, 'nombre' => 'SANTO DOMINGO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 697, 'nombre' => 'SANTUARIO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 736, 'nombre' => 'SEGOVIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 756, 'nombre' => 'SONSON', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 761, 'nombre' => 'SOPETRAN', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 789, 'nombre' => 'TAMESIS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 790, 'nombre' => 'TARAZA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 792, 'nombre' => 'TARSO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 809, 'nombre' => 'TITIRIBI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 819, 'nombre' => 'TOLEDO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 837, 'nombre' => 'TURBO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 842, 'nombre' => 'URAMITA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 847, 'nombre' => 'URRAO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 854, 'nombre' => 'VALDIVIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 856, 'nombre' => 'VALPARAISO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 858, 'nombre' => 'VEGACHI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 861, 'nombre' => 'VENECIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 873, 'nombre' => 'VIGIA DEL FUERTE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 885, 'nombre' => 'YALI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 887, 'nombre' => 'YARUMAL', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 890, 'nombre' => 'YOLOMBO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 893, 'nombre' => 'YONDO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 1, 'codigo' => 895, 'nombre' => 'ZARAGOZA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 1, 'nombre' => 'BARRANQUILLA (DISTRITO ESPECIAL INDUSTRIAL Y PORTUARIO DE BARRANQUILLA)', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 78, 'nombre' => 'BARANOA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 137, 'nombre' => 'CAMPO DE LA CRUZ', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 141, 'nombre' => 'CANDELARIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 296, 'nombre' => 'GALAPA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 372, 'nombre' => 'JUAN DE ACOSTA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 421, 'nombre' => 'LURUACO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 433, 'nombre' => 'MALAMBO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 436, 'nombre' => 'MANATI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 520, 'nombre' => 'PALMAR DE VARELA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 549, 'nombre' => 'PIOJO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 558, 'nombre' => 'POLO NUEVO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 560, 'nombre' => 'PONEDERA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 573, 'nombre' => 'PUERTO COLOMBIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 606, 'nombre' => 'REPELON', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 634, 'nombre' => 'SABANAGRANDE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 638, 'nombre' => 'SABANALARGA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 675, 'nombre' => 'SANTA LUCIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 685, 'nombre' => 'SANTO TOMAS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 758, 'nombre' => 'SOLEDAD', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 770, 'nombre' => 'SUAN', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 832, 'nombre' => 'TUBARA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 2, 'codigo' => 849, 'nombre' => 'USIACURI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 1, 'nombre' => 'Santa Fe de Bogotá', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 1, 'nombre' => 'USAQUEN', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 2, 'nombre' => 'CHAPINERO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 3, 'nombre' => 'SANTA FE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 4, 'nombre' => 'SAN CRISTOBAL', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 5, 'nombre' => 'USME', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 6, 'nombre' => 'TUNJUELITO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 7, 'nombre' => 'BOSA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 8, 'nombre' => 'KENNEDY', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 9, 'nombre' => 'FONTIBON', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 10, 'nombre' => 'ENGATIVA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 11, 'nombre' => 'SUBA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 12, 'nombre' => 'BARRIOS UNIDOS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 13, 'nombre' => 'TEUSAQUILLO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 14, 'nombre' => 'MARTIRES', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 15, 'nombre' => 'ANTONIO NARIÑO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 16, 'nombre' => 'PUENTE ARANDA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 17, 'nombre' => 'CANDELARIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 18, 'nombre' => 'RAFAEL URIBE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 19, 'nombre' => 'CIUDAD BOLIVAR', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 3, 'codigo' => 20, 'nombre' => 'SUMAPAZ', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 1, 'nombre' => 'CARTAGENA (DISTRITO TURISTICO Y CULTURAL DE CARTAGENA)','created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 6, 'nombre' => 'ACHI', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 30, 'nombre' => 'ALTOS DEL ROSARIO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 42, 'nombre' => 'ARENAL', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 52, 'nombre' => 'ARJONA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 62, 'nombre' => 'ARROYOHONDO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 74, 'nombre' => 'BARRANCO DE LOBA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 140, 'nombre' => 'CALAMAR', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 160, 'nombre' => 'CANTAGALLO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 188, 'nombre' => 'CICUCO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 212, 'nombre' => 'CORDOBA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 222, 'nombre' => 'CLEMENCIA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 244, 'nombre' => 'EL CARMEN DE BOLIVAR', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 248, 'nombre' => 'EL GUAMO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 268, 'nombre' => 'EL PEÑON', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 300, 'nombre' => 'HATILLO DE LOBA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 430, 'nombre' => 'MAGANGUE', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 433, 'nombre' => 'MAHATES', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 440, 'nombre' => 'MARGARITA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 442, 'nombre' => 'MARIA LA BAJA', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 458, 'nombre' => 'MONTECRISTO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 468, 'nombre' => 'MOMPOS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 473, 'nombre' => 'MORALES', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 549, 'nombre' => 'PINILLOS', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 580, 'nombre' => 'REGIDOR', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 600, 'nombre' => 'RIO VIEJO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 620, 'nombre' => 'SAN CRISTOBAL', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 647, 'nombre' => 'SAN ESTANISLAO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 650, 'nombre' => 'SAN FERNANDO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 654, 'nombre' => 'SAN JACINTO', 'created_at' => $now, 'updated_at' => $now],
            ['departamento_id' => 4, 'codigo' => 655, 'nombre' => 'SAN JACINTO DEL CAUCA', 'created_at' => $now, 'updated_at' => $now],
        ]

        DB::table('municipios')->insert($municipios);

    }
}
